clear all

start = clib.ArrtsLibrary.State(5, 60, 0);
goal = clib.ArrtsLibrary.State(100, 60, 0);

obstacles = {clib.ArrtsLibrary.Obstacle(80,40,8),...
clib.ArrtsLibrary.Obstacle(73,30,8),...
clib.ArrtsLibrary.Obstacle(63,25,8),...
clib.ArrtsLibrary.Obstacle(53,25,8),...
clib.ArrtsLibrary.Obstacle(43,26,8),...
clib.ArrtsLibrary.Obstacle(33,25,8),...
clib.ArrtsLibrary.Obstacle(28,35,8),...
clib.ArrtsLibrary.Obstacle(25,47,8),...
clib.ArrtsLibrary.Obstacle(25,57,8),...
clib.ArrtsLibrary.Obstacle(25,67,8),...
clib.ArrtsLibrary.Obstacle(25,77,8),...
clib.ArrtsLibrary.Obstacle(35,80,8),...
clib.ArrtsLibrary.Obstacle(40,80,8),...
clib.ArrtsLibrary.Obstacle(45,80,8),...
clib.ArrtsLibrary.Obstacle(80,80,8),...
clib.ArrtsLibrary.Obstacle(85,80,8),...
clib.ArrtsLibrary.Obstacle(90,80,8),...
clib.ArrtsLibrary.Obstacle(95,80,8),...
clib.ArrtsLibrary.Obstacle(100,80,8),...
clib.ArrtsLibrary.Obstacle(100,0,8),...
clib.ArrtsLibrary.Obstacle(100,5,8),...
clib.ArrtsLibrary.Obstacle(100,10,8),...
clib.ArrtsLibrary.Obstacle(60,100,8)};

obstacleArray = clib.array.ArrtsLibrary.Obstacle(numel(obstacles));
for i = 1:numel(obstacles)
    obstacleArray(i) = obstacles{i};
end

params = clib.ArrtsLibrary.ArrtsParams(start, goal, obstacleArray, 2.5);
service = clib.ArrtsLibrary.ArrtsService();
states = service.calculatePath(params);

for i = 1:states.Dimensions
    text = ['(', num2str(states(i).x), ',', num2str(states(i).y), ',', num2str(states(i).theta), ')'];
    disp(text)
end
